hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - model=cnn_small,cnn_deep
    - training.epochs=300
    - training.batch_size=64
    - training.learning_rate=0.0003
    - training.loss.temperature=0.15
    - model.embedding_dim=128
  job:
    name: train
    chdir: null
    override_dirname: model.embedding_dim=128,model=cnn_small,cnn_deep,training.batch_size=64,training.epochs=300,training.learning_rate=0.0003,training.loss.temperature=0.15
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/brantlab/projects/phoneme_contrast
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/brantlab/projects/phoneme_contrast/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model: cnn_small
      data: default
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
experiment:
  name: phoneme_contrast
  seed: 42
  output_dir: ${hydra:runtime.output_dir}
data:
  data_path: data/raw/New Stimuli 9-8-2024
  target_sr: 16000
  max_length_ms: 2000
  train_split: 0.85
  feature_extractor:
    type: mfcc
    mfcc_params:
      n_mfcc: 40
      n_fft: 400
      hop_length: 160
  augmentation:
    time_stretch:
      enabled: true
      min_rate: 0.9
      max_rate: 1.1
      prob: 0.5
    noise:
      enabled: true
      min_snr: 0.001
      max_snr: 0.005
      prob: 0.3
    time_mask:
      enabled: true
      max_width: 30
      prob: 0.5
    freq_mask:
      enabled: true
      max_width: 10
      prob: 0.5
  contrastive:
    views_per_sample: 2
    classes_per_batch: 6
    samples_per_class: 2
model:
  type: phoneme_cnn
  in_channels: 1
  embedding_dim: 128
  use_attention: true
  dropout_rate: 0.1
training:
  epochs: 300
  learning_rate: 0.0003
  weight_decay: 0.0001
  loss:
    type: supervised_contrastive
    temperature: 0.15
  eval_every: 5
  eval_classifier_every: 5
  save_every: 10
  best_metric: rf_accuracy
  batch_size: 64
  num_workers: 0
  pin_memory: null
  gradient_clip_val: 1.0
  use_scheduler: true
  min_lr: 1.0e-06
logging:
  level: info
  wandb:
    enabled: false
    project: phoneme_contrast
