# configs/config.yaml
defaults:
  - _self_
  - data: default
  - model: cnn_small

experiment:
  name: phoneme_contrast
  seed: 42
  output_dir: ${hydra:runtime.output_dir}

data:
  data_path: data/raw/New Stimuli 9-8-2024
  target_sr: 16000
  max_length_ms: 2000
  train_split: 0.85

model:
  type: phoneme_cnn
  in_channels: 1
  embedding_dim: 128
  use_attention: true
  dropout_rate: 0.1

training:
  epochs: 100
  learning_rate: 3e-4
  weight_decay: 1e-4
  
  # Loss configuration
  loss:
    type: supervised_contrastive
    temperature: 0.07
    
  # Evaluation settings
  eval_every: 5
  eval_classifier_every: 5  # Run classifier evaluation every 5 epochs
  save_every: 10
  
  # What metric to use for best model selection
  best_metric: rf_accuracy  # Options: loss, linear_accuracy, rf_accuracy
  
  # System-dependent
  batch_size: 16
  num_workers: 0
  pin_memory: null
  
  # Training options
  gradient_clip_val: 1.0
  
  # Scheduler
  use_scheduler: true
  min_lr: 1e-6

logging:
  level: info
  wandb:
    enabled: false
    project: phoneme_contrast